# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/spasz/python/qursor-vision/yaya/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1643, 898)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.centralwidget.sizePolicy().hasHeightForWidth()
        )
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter_4 = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_4.sizePolicy().hasHeightForWidth())
        self.splitter_4.setSizePolicy(sizePolicy)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter_4)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayoutLeft = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayoutLeft.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayoutLeft.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutLeft.setObjectName("verticalLayoutLeft")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.prevFileButton = QtWidgets.QToolButton(self.verticalLayoutWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/icons/16x16/media-skip-backward.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.prevFileButton.setIcon(icon)
        self.prevFileButton.setObjectName("prevFileButton")
        self.horizontalLayout.addWidget(self.prevFileButton)
        self.fileNumberSliderLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.fileNumberSliderLabel.setObjectName("fileNumberSliderLabel")
        self.horizontalLayout.addWidget(self.fileNumberSliderLabel)
        self.nextFileButton = QtWidgets.QToolButton(self.verticalLayoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap(":/icons/16x16/media-skip-forward.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.nextFileButton.setIcon(icon1)
        self.nextFileButton.setObjectName("nextFileButton")
        self.horizontalLayout.addWidget(self.nextFileButton)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.imageScalingComboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.imageScalingComboBox.setObjectName("imageScalingComboBox")
        self.imageScalingComboBox.addItem("")
        self.imageScalingComboBox.addItem("")
        self.imageScalingComboBox.addItem("")
        self.horizontalLayout.addWidget(self.imageScalingComboBox)
        self.progressBar = QtWidgets.QProgressBar(self.verticalLayoutWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.verticalLayoutLeft.addLayout(self.horizontalLayout)
        self.viewerEditor = ViewerEditorImage(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewerEditor.sizePolicy().hasHeightForWidth())
        self.viewerEditor.setSizePolicy(sizePolicy)
        self.viewerEditor.setMinimumSize(QtCore.QSize(800, 100))
        self.viewerEditor.setObjectName("viewerEditor")
        self.verticalLayoutLeft.addWidget(self.viewerEditor)
        self.layoutWidget = QtWidgets.QWidget(self.splitter_4)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayoutRight = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayoutRight.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayoutRight.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutRight.setObjectName("verticalLayoutRight")
        self.sliderLayout = QtWidgets.QHBoxLayout()
        self.sliderLayout.setObjectName("sliderLayout")
        self.fileLabel = QtWidgets.QLabel(self.layoutWidget)
        self.fileLabel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileLabel.sizePolicy().hasHeightForWidth())
        self.fileLabel.setSizePolicy(sizePolicy)
        self.fileLabel.setMinimumSize(QtCore.QSize(300, 32))
        self.fileLabel.setObjectName("fileLabel")
        self.sliderLayout.addWidget(self.fileLabel)
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.sliderLayout.addItem(spacerItem)
        self.verticalLayoutRight.addLayout(self.sliderLayout)
        self.fileSummaryLabel = QtWidgets.QLabel(self.layoutWidget)
        self.fileSummaryLabel.setTextFormat(QtCore.Qt.MarkdownText)
        self.fileSummaryLabel.setObjectName("fileSummaryLabel")
        self.verticalLayoutRight.addWidget(self.fileSummaryLabel)
        self.fileSelectorTableWidget = QtWidgets.QTableWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.fileSelectorTableWidget.sizePolicy().hasHeightForWidth()
        )
        self.fileSelectorTableWidget.setSizePolicy(sizePolicy)
        self.fileSelectorTableWidget.setMinimumSize(QtCore.QSize(0, 300))
        self.fileSelectorTableWidget.setVerticalScrollBarPolicy(
            QtCore.Qt.ScrollBarAlwaysOn
        )
        self.fileSelectorTableWidget.setSizeAdjustPolicy(
            QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow
        )
        self.fileSelectorTableWidget.setSelectionMode(
            QtWidgets.QAbstractItemView.SingleSelection
        )
        self.fileSelectorTableWidget.setSelectionBehavior(
            QtWidgets.QAbstractItemView.SelectRows
        )
        self.fileSelectorTableWidget.setObjectName("fileSelectorTableWidget")
        self.fileSelectorTableWidget.setColumnCount(0)
        self.fileSelectorTableWidget.setRowCount(0)
        self.verticalLayoutRight.addWidget(self.fileSelectorTableWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.SaveFileAnnotationsButton = QtWidgets.QPushButton(self.layoutWidget)
        self.SaveFileAnnotationsButton.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        icon2 = QtGui.QIcon()
        icon2.addPixmap(
            QtGui.QPixmap(":/icons/16x16/document-save-as.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.SaveFileAnnotationsButton.setIcon(icon2)
        self.SaveFileAnnotationsButton.setObjectName("SaveFileAnnotationsButton")
        self.horizontalLayout_2.addWidget(self.SaveFileAnnotationsButton)
        self.CacheImageButton = QtWidgets.QPushButton(self.layoutWidget)
        self.CacheImageButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(
            QtGui.QPixmap(":/icons/32x32/document-save.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.CacheImageButton.setIcon(icon3)
        self.CacheImageButton.setObjectName("CacheImageButton")
        self.horizontalLayout_2.addWidget(self.CacheImageButton)
        self.DeleteImageAnnotationsButton = QtWidgets.QPushButton(self.layoutWidget)
        self.DeleteImageAnnotationsButton.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        icon4 = QtGui.QIcon()
        icon4.addPixmap(
            QtGui.QPixmap(":/icons/16x16/process-stop.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.DeleteImageAnnotationsButton.setIcon(icon4)
        self.DeleteImageAnnotationsButton.setObjectName("DeleteImageAnnotationsButton")
        self.horizontalLayout_2.addWidget(self.DeleteImageAnnotationsButton)
        self.DeleteNotAnnotatedFilesButton = QtWidgets.QPushButton(self.layoutWidget)
        self.DeleteNotAnnotatedFilesButton.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        icon5 = QtGui.QIcon()
        icon5.addPixmap(
            QtGui.QPixmap(":/icons/32x32/process-stop.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.DeleteNotAnnotatedFilesButton.setIcon(icon5)
        self.DeleteNotAnnotatedFilesButton.setObjectName(
            "DeleteNotAnnotatedFilesButton"
        )
        self.horizontalLayout_2.addWidget(self.DeleteNotAnnotatedFilesButton)
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayoutRight.addLayout(self.horizontalLayout_2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.paintCircleButton = QtWidgets.QPushButton(self.layoutWidget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(
            QtGui.QPixmap(":/icons/32x32/list-add.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.paintCircleButton.setIcon(icon6)
        self.paintCircleButton.setCheckable(True)
        self.paintCircleButton.setObjectName("paintCircleButton")
        self.gridLayout_2.addWidget(self.paintCircleButton, 0, 6, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(90, 0))
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.hideLabelsButton = QtWidgets.QPushButton(self.layoutWidget)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(
            QtGui.QPixmap(":/icons/32x32/go-jump.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.hideLabelsButton.setIcon(icon7)
        self.hideLabelsButton.setObjectName("hideLabelsButton")
        self.gridLayout_2.addWidget(self.hideLabelsButton, 0, 7, 1, 1)
        self.removeAnnotationsButton = QtWidgets.QPushButton(self.layoutWidget)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(
            QtGui.QPixmap(":/icons/16x16/list-remove.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.removeAnnotationsButton.setIcon(icon8)
        self.removeAnnotationsButton.setCheckable(True)
        self.removeAnnotationsButton.setObjectName("removeAnnotationsButton")
        self.gridLayout_2.addWidget(self.removeAnnotationsButton, 0, 4, 1, 1)
        self.ClearAnnotationsButton = QtWidgets.QPushButton(self.layoutWidget)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(
            QtGui.QPixmap(":/icons/16x16/edit-clear.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.ClearAnnotationsButton.setIcon(icon9)
        self.ClearAnnotationsButton.setObjectName("ClearAnnotationsButton")
        self.gridLayout_2.addWidget(self.ClearAnnotationsButton, 0, 5, 1, 1)
        self.detectAnnotationsButton = QtWidgets.QPushButton(self.layoutWidget)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(
            QtGui.QPixmap(":/icons/16x16/camera-photo.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.detectAnnotationsButton.setIcon(icon10)
        self.detectAnnotationsButton.setObjectName("detectAnnotationsButton")
        self.gridLayout_2.addWidget(self.detectAnnotationsButton, 1, 2, 1, 1)
        self.addAnnotationsButton = QtWidgets.QPushButton(self.layoutWidget)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(
            QtGui.QPixmap(":/icons/16x16/list-add.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.addAnnotationsButton.setIcon(icon11)
        self.addAnnotationsButton.setCheckable(True)
        self.addAnnotationsButton.setFlat(False)
        self.addAnnotationsButton.setObjectName("addAnnotationsButton")
        self.gridLayout_2.addWidget(self.addAnnotationsButton, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.gridLayout_2.addItem(spacerItem2, 0, 10, 1, 1)
        self.renameAnnotationsButton = QtWidgets.QPushButton(self.layoutWidget)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(
            QtGui.QPixmap(":/icons/32x32/accessories-text-editor.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.renameAnnotationsButton.setIcon(icon12)
        self.renameAnnotationsButton.setCheckable(True)
        self.renameAnnotationsButton.setObjectName("renameAnnotationsButton")
        self.gridLayout_2.addWidget(self.renameAnnotationsButton, 0, 3, 1, 1)
        self.hideAnnotationsButton = QtWidgets.QPushButton(self.layoutWidget)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(
            QtGui.QPixmap(":/icons/16x16/go-jump.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.hideAnnotationsButton.setIcon(icon13)
        self.hideAnnotationsButton.setObjectName("hideAnnotationsButton")
        self.gridLayout_2.addWidget(self.hideAnnotationsButton, 0, 8, 1, 1)
        self.detFilterButton = QtWidgets.QPushButton(self.layoutWidget)
        self.detFilterButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(
            QtGui.QPixmap(":/icons/32x32/edit-find.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.detFilterButton.setIcon(icon14)
        self.detFilterButton.setObjectName("detFilterButton")
        self.gridLayout_2.addWidget(self.detFilterButton, 1, 5, 1, 1)
        self.annotationFilterButton = QtWidgets.QPushButton(self.layoutWidget)
        self.annotationFilterButton.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.annotationFilterButton.setIcon(icon14)
        self.annotationFilterButton.setObjectName("annotationFilterButton")
        self.gridLayout_2.addWidget(self.annotationFilterButton, 1, 4, 1, 1)
        self.yoloWorldButton = QtWidgets.QPushButton(self.layoutWidget)
        self.yoloWorldButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon15 = QtGui.QIcon()
        icon15.addPixmap(
            QtGui.QPixmap(":/icons/32x32/camera-photo.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.yoloWorldButton.setIcon(icon15)
        self.yoloWorldButton.setObjectName("yoloWorldButton")
        self.gridLayout_2.addWidget(self.yoloWorldButton, 1, 3, 1, 1)
        self.verticalLayoutRight.addLayout(self.gridLayout_2)
        self.toolSettingsStackedWidget = QtWidgets.QStackedWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.toolSettingsStackedWidget.sizePolicy().hasHeightForWidth()
        )
        self.toolSettingsStackedWidget.setSizePolicy(sizePolicy)
        self.toolSettingsStackedWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.toolSettingsStackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.toolSettingsStackedWidget.setLineWidth(1)
        self.toolSettingsStackedWidget.setObjectName("toolSettingsStackedWidget")
        self.pageAnnotations = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.pageAnnotations.sizePolicy().hasHeightForWidth()
        )
        self.pageAnnotations.setSizePolicy(sizePolicy)
        self.pageAnnotations.setObjectName("pageAnnotations")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.pageAnnotations)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.detectorClassesLabel = QtWidgets.QLabel(self.pageAnnotations)
        self.detectorClassesLabel.setObjectName("detectorClassesLabel")
        self.verticalLayout_2.addWidget(self.detectorClassesLabel)
        self.labelsListWidget = QtWidgets.QListWidget(self.pageAnnotations)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.labelsListWidget.sizePolicy().hasHeightForWidth()
        )
        self.labelsListWidget.setSizePolicy(sizePolicy)
        self.labelsListWidget.setMinimumSize(QtCore.QSize(0, 80))
        self.labelsListWidget.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.labelsListWidget.setSelectionMode(
            QtWidgets.QAbstractItemView.SingleSelection
        )
        self.labelsListWidget.setSelectionBehavior(
            QtWidgets.QAbstractItemView.SelectItems
        )
        self.labelsListWidget.setObjectName("labelsListWidget")
        self.verticalLayout_2.addWidget(self.labelsListWidget)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame = QtWidgets.QFrame(self.pageAnnotations)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.button2 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button2.sizePolicy().hasHeightForWidth())
        self.button2.setSizePolicy(sizePolicy)
        self.button2.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.button2.setFont(font)
        self.button2.setFlat(True)
        self.button2.setObjectName("button2")
        self.horizontalLayout_7.addWidget(self.button2)
        self.button5 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button5.sizePolicy().hasHeightForWidth())
        self.button5.setSizePolicy(sizePolicy)
        self.button5.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.button5.setFont(font)
        self.button5.setFlat(True)
        self.button5.setObjectName("button5")
        self.horizontalLayout_7.addWidget(self.button5)
        self.button7 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button7.sizePolicy().hasHeightForWidth())
        self.button7.setSizePolicy(sizePolicy)
        self.button7.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.button7.setFont(font)
        self.button7.setFlat(True)
        self.button7.setObjectName("button7")
        self.horizontalLayout_7.addWidget(self.button7)
        self.button8 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button8.sizePolicy().hasHeightForWidth())
        self.button8.setSizePolicy(sizePolicy)
        self.button8.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.button8.setFont(font)
        self.button8.setFlat(True)
        self.button8.setObjectName("button8")
        self.horizontalLayout_7.addWidget(self.button8)
        self.button1 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button1.sizePolicy().hasHeightForWidth())
        self.button1.setSizePolicy(sizePolicy)
        self.button1.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.button1.setFont(font)
        self.button1.setDefault(False)
        self.button1.setFlat(True)
        self.button1.setObjectName("button1")
        self.horizontalLayout_7.addWidget(self.button1)
        self.buttonOffset = QtWidgets.QPushButton(self.frame)
        self.buttonOffset.setMaximumSize(QtCore.QSize(22, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.buttonOffset.setFont(font)
        self.buttonOffset.setFlat(True)
        self.buttonOffset.setObjectName("buttonOffset")
        self.horizontalLayout_7.addWidget(self.buttonOffset)
        self.button9 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button9.sizePolicy().hasHeightForWidth())
        self.button9.setSizePolicy(sizePolicy)
        self.button9.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.button9.setFont(font)
        self.button9.setFlat(True)
        self.button9.setObjectName("button9")
        self.horizontalLayout_7.addWidget(self.button9)
        self.button10 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button10.sizePolicy().hasHeightForWidth())
        self.button10.setSizePolicy(sizePolicy)
        self.button10.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.button10.setFont(font)
        self.button10.setFlat(True)
        self.button10.setObjectName("button10")
        self.horizontalLayout_7.addWidget(self.button10)
        self.button12 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button12.sizePolicy().hasHeightForWidth())
        self.button12.setSizePolicy(sizePolicy)
        self.button12.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.button12.setFont(font)
        self.button12.setFlat(True)
        self.button12.setObjectName("button12")
        self.horizontalLayout_7.addWidget(self.button12)
        self.button3 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button3.sizePolicy().hasHeightForWidth())
        self.button3.setSizePolicy(sizePolicy)
        self.button3.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.button3.setFont(font)
        self.button3.setFlat(True)
        self.button3.setObjectName("button3")
        self.horizontalLayout_7.addWidget(self.button3)
        self.button11 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button11.sizePolicy().hasHeightForWidth())
        self.button11.setSizePolicy(sizePolicy)
        self.button11.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.button11.setFont(font)
        self.button11.setFlat(True)
        self.button11.setObjectName("button11")
        self.horizontalLayout_7.addWidget(self.button11)
        self.button4 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button4.sizePolicy().hasHeightForWidth())
        self.button4.setSizePolicy(sizePolicy)
        self.button4.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.button4.setFont(font)
        self.button4.setFlat(True)
        self.button4.setObjectName("button4")
        self.horizontalLayout_7.addWidget(self.button4)
        self.button6 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button6.sizePolicy().hasHeightForWidth())
        self.button6.setSizePolicy(sizePolicy)
        self.button6.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.button6.setFont(font)
        self.button6.setFlat(True)
        self.button6.setObjectName("button6")
        self.horizontalLayout_7.addWidget(self.button6)
        self.horizontalLayout_6.addWidget(self.frame)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        spacerItem3 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout_2.addItem(spacerItem3)
        self.toolSettingsStackedWidget.addWidget(self.pageAnnotations)
        self.pageDetector = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageDetector.sizePolicy().hasHeightForWidth())
        self.pageDetector.setSizePolicy(sizePolicy)
        self.pageDetector.setObjectName("pageDetector")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.pageDetector)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.detectorDetails = QtWidgets.QLabel(self.pageDetector)
        self.detectorDetails.setTextFormat(QtCore.Qt.MarkdownText)
        self.detectorDetails.setObjectName("detectorDetails")
        self.verticalLayout_4.addWidget(self.detectorDetails)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.detectorConfidenceLabel = QtWidgets.QLabel(self.pageDetector)
        self.detectorConfidenceLabel.setObjectName("detectorConfidenceLabel")
        self.horizontalLayout_9.addWidget(self.detectorConfidenceLabel)
        self.imageStrategyCombo = QtWidgets.QComboBox(self.pageDetector)
        self.imageStrategyCombo.setObjectName("imageStrategyCombo")
        self.imageStrategyCombo.addItem("")
        self.horizontalLayout_9.addWidget(self.imageStrategyCombo)
        spacerItem4 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_9.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.detectorConfidenceSlider = QtWidgets.QSlider(self.pageDetector)
        self.detectorConfidenceSlider.setMaximum(100)
        self.detectorConfidenceSlider.setOrientation(QtCore.Qt.Horizontal)
        self.detectorConfidenceSlider.setInvertedAppearance(False)
        self.detectorConfidenceSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.detectorConfidenceSlider.setObjectName("detectorConfidenceSlider")
        self.verticalLayout_4.addWidget(self.detectorConfidenceSlider)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.detectorNmsLabel = QtWidgets.QLabel(self.pageDetector)
        self.detectorNmsLabel.setObjectName("detectorNmsLabel")
        self.horizontalLayout_8.addWidget(self.detectorNmsLabel)
        self.detectorNmsCombo = QtWidgets.QComboBox(self.pageDetector)
        self.detectorNmsCombo.setObjectName("detectorNmsCombo")
        self.detectorNmsCombo.addItem("")
        self.detectorNmsCombo.addItem("")
        self.horizontalLayout_8.addWidget(self.detectorNmsCombo)
        spacerItem5 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_8.addItem(spacerItem5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.detectorNmsSlider = QtWidgets.QSlider(self.pageDetector)
        self.detectorNmsSlider.setMaximum(100)
        self.detectorNmsSlider.setOrientation(QtCore.Qt.Horizontal)
        self.detectorNmsSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.detectorNmsSlider.setObjectName("detectorNmsSlider")
        self.verticalLayout_4.addWidget(self.detectorNmsSlider)
        spacerItem6 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout_4.addItem(spacerItem6)
        self.toolSettingsStackedWidget.addWidget(self.pageDetector)
        self.pageYoloWorld = QtWidgets.QWidget()
        self.pageYoloWorld.setObjectName("pageYoloWorld")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.pageYoloWorld)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.detectorEnabled = QtWidgets.QCheckBox(self.pageYoloWorld)
        self.detectorEnabled.setChecked(True)
        self.detectorEnabled.setObjectName("detectorEnabled")
        self.horizontalLayout_10.addWidget(self.detectorEnabled)
        self.label_6 = QtWidgets.QLabel(self.pageYoloWorld)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_10.addWidget(self.label_6)
        spacerItem7 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_10.addItem(spacerItem7)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.yoloWorldConfidenceLabel = QtWidgets.QLabel(self.pageYoloWorld)
        self.yoloWorldConfidenceLabel.setObjectName("yoloWorldConfidenceLabel")
        self.horizontalLayout_3.addWidget(self.yoloWorldConfidenceLabel)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.yoloWorldConfidenceSlider = QtWidgets.QSlider(self.pageYoloWorld)
        self.yoloWorldConfidenceSlider.setOrientation(QtCore.Qt.Horizontal)
        self.yoloWorldConfidenceSlider.setObjectName("yoloWorldConfidenceSlider")
        self.verticalLayout_7.addWidget(self.yoloWorldConfidenceSlider)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.pageYoloWorld)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.yoloWorldPrompt = QtWidgets.QLineEdit(self.pageYoloWorld)
        self.yoloWorldPrompt.setObjectName("yoloWorldPrompt")
        self.verticalLayout_7.addWidget(self.yoloWorldPrompt)
        spacerItem8 = QtWidgets.QSpacerItem(
            20, 175, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout_7.addItem(spacerItem8)
        self.toolSettingsStackedWidget.addWidget(self.pageYoloWorld)
        self.pageCircle = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageCircle.sizePolicy().hasHeightForWidth())
        self.pageCircle.setSizePolicy(sizePolicy)
        self.pageCircle.setObjectName("pageCircle")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.pageCircle)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.paintLabel = QtWidgets.QLabel(self.pageCircle)
        self.paintLabel.setObjectName("paintLabel")
        self.horizontalLayout_5.addWidget(self.paintLabel)
        self.paintSizeSlider = QtWidgets.QSlider(self.pageCircle)
        self.paintSizeSlider.setMinimum(5)
        self.paintSizeSlider.setMaximum(55)
        self.paintSizeSlider.setSingleStep(10)
        self.paintSizeSlider.setProperty("value", 25)
        self.paintSizeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.paintSizeSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.paintSizeSlider.setObjectName("paintSizeSlider")
        self.horizontalLayout_5.addWidget(self.paintSizeSlider)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem9 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout.addItem(spacerItem9)
        self.toolSettingsStackedWidget.addWidget(self.pageCircle)
        self.pageKeycodes = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageKeycodes.sizePolicy().hasHeightForWidth())
        self.pageKeycodes.setSizePolicy(sizePolicy)
        self.pageKeycodes.setObjectName("pageKeycodes")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.pageKeycodes)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.toolSettingsStackedWidget.addWidget(self.pageKeycodes)
        self.pageAnnFilter = QtWidgets.QWidget()
        self.pageAnnFilter.setObjectName("pageAnnFilter")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.pageAnnFilter)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.annotationsFilterGrid = QtWidgets.QGridLayout()
        self.annotationsFilterGrid.setObjectName("annotationsFilterGrid")
        self.label_3 = QtWidgets.QLabel(self.pageAnnFilter)
        self.label_3.setObjectName("label_3")
        self.annotationsFilterGrid.addWidget(self.label_3, 0, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.annotationsFilterGrid)
        spacerItem10 = QtWidgets.QSpacerItem(
            20, 289, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout_5.addItem(spacerItem10)
        self.toolSettingsStackedWidget.addWidget(self.pageAnnFilter)
        self.pageDetFilter = QtWidgets.QWidget()
        self.pageDetFilter.setObjectName("pageDetFilter")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.pageDetFilter)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.detectionsFilterGrid = QtWidgets.QGridLayout()
        self.detectionsFilterGrid.setObjectName("detectionsFilterGrid")
        self.label_5 = QtWidgets.QLabel(self.pageDetFilter)
        self.label_5.setObjectName("label_5")
        self.detectionsFilterGrid.addWidget(self.label_5, 0, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.detectionsFilterGrid)
        spacerItem11 = QtWidgets.QSpacerItem(
            20, 289, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout_6.addItem(spacerItem11)
        self.toolSettingsStackedWidget.addWidget(self.pageDetFilter)
        self.verticalLayoutRight.addWidget(self.toolSettingsStackedWidget)
        self.gridLayout.addWidget(self.splitter_4, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1643, 30))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuPomoc = QtWidgets.QMenu(self.menubar)
        self.menuPomoc.setObjectName("menuPomoc")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuAnnotations_type = QtWidgets.QMenu(self.menuView)
        self.menuAnnotations_type.setObjectName("menuAnnotations_type")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOtw_rz = QtWidgets.QAction(MainWindow)
        self.actionOtw_rz.setObjectName("actionOtw_rz")
        self.actionZamknij = QtWidgets.QAction(MainWindow)
        self.actionZamknij.setObjectName("actionZamknij")
        self.actionO_programie = QtWidgets.QAction(MainWindow)
        self.actionO_programie.setObjectName("actionO_programie")
        self.actionOtworzLokacje = QtWidgets.QAction(MainWindow)
        self.actionOtworzLokacje.setObjectName("actionOtworzLokacje")
        self.actionZamknijProgram = QtWidgets.QAction(MainWindow)
        self.actionZamknijProgram.setObjectName("actionZamknijProgram")
        self.actionZapisz = QtWidgets.QAction(MainWindow)
        self.actionZapisz.setObjectName("actionZapisz")
        self.actionNextLocation = QtWidgets.QAction(MainWindow)
        self.actionNextLocation.setObjectName("actionNextLocation")
        self.actionPrevLocation = QtWidgets.QAction(MainWindow)
        self.actionPrevLocation.setObjectName("actionPrevLocation")
        self.actionMountRO = QtWidgets.QAction(MainWindow)
        self.actionMountRO.setObjectName("actionMountRO")
        self.actionNextConfiguration = QtWidgets.QAction(MainWindow)
        self.actionNextConfiguration.setObjectName("actionNextConfiguration")
        self.actionPrevConfiguration = QtWidgets.QAction(MainWindow)
        self.actionPrevConfiguration.setObjectName("actionPrevConfiguration")
        self.actionSave_screenshoot = QtWidgets.QAction(MainWindow)
        self.actionSave_screenshoot.setObjectName("actionSave_screenshoot")
        self.actionSave_copy = QtWidgets.QAction(MainWindow)
        self.actionSave_copy.setObjectName("actionSave_copy")
        self.action_annotations_default = QtWidgets.QAction(MainWindow)
        self.action_annotations_default.setCheckable(True)
        self.action_annotations_default.setObjectName("action_annotations_default")
        self.action_annotations_confidence_heat = QtWidgets.QAction(MainWindow)
        self.action_annotations_confidence_heat.setCheckable(True)
        self.action_annotations_confidence_heat.setObjectName(
            "action_annotations_confidence_heat"
        )
        self.menuMenu.addAction(self.actionOtworzLokacje)
        self.menuMenu.addAction(self.actionZapisz)
        self.menuMenu.addAction(self.actionZamknijProgram)
        self.menuEdit.addAction(self.actionSave_screenshoot)
        self.menuEdit.addAction(self.actionSave_copy)
        self.menuAnnotations_type.addAction(self.action_annotations_default)
        self.menuAnnotations_type.addAction(self.action_annotations_confidence_heat)
        self.menuView.addAction(self.menuAnnotations_type.menuAction())
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuPomoc.menuAction())

        self.retranslateUi(MainWindow)
        self.toolSettingsStackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YAYA - YOLO annoter"))
        self.prevFileButton.setText(_translate("MainWindow", "..."))
        self.prevFileButton.setShortcut(_translate("MainWindow", ","))
        self.fileNumberSliderLabel.setText(_translate("MainWindow", "Slider label"))
        self.nextFileButton.setText(_translate("MainWindow", "..."))
        self.nextFileButton.setShortcut(_translate("MainWindow", "."))
        self.label_4.setText(_translate("MainWindow", "Image scaling:"))
        self.imageScalingComboBox.setItemText(0, _translate("MainWindow", "Resize"))
        self.imageScalingComboBox.setItemText(
            1, _translate("MainWindow", "ResizeAspectRatio")
        )
        self.imageScalingComboBox.setItemText(
            2, _translate("MainWindow", "OriginalSize")
        )
        self.progressBar.setFormat(_translate("MainWindow", "Annotated %p%"))
        self.fileLabel.setText(_translate("MainWindow", "Filename (number/all)"))
        self.fileSummaryLabel.setText(_translate("MainWindow", "TextLabel"))
        self.fileSelectorTableWidget.setSortingEnabled(True)
        self.label_2.setText(_translate("MainWindow", "Image"))
        self.SaveFileAnnotationsButton.setText(_translate("MainWindow", "(S)ave"))
        self.SaveFileAnnotationsButton.setShortcut(_translate("MainWindow", "S"))
        self.CacheImageButton.setText(_translate("MainWindow", "Cache(Y)"))
        self.CacheImageButton.setShortcut(_translate("MainWindow", "Y"))
        self.DeleteImageAnnotationsButton.setText(_translate("MainWindow", "(X)Delete"))
        self.DeleteImageAnnotationsButton.setShortcut(_translate("MainWindow", "X"))
        self.DeleteNotAnnotatedFilesButton.setText(
            _translate("MainWindow", "Delete not annotated")
        )
        self.paintCircleButton.setText(_translate("MainWindow", "Circl(e)"))
        self.paintCircleButton.setShortcut(_translate("MainWindow", "E"))
        self.label.setText(_translate("MainWindow", "Annotations"))
        self.hideLabelsButton.setText(_translate("MainWindow", "(L)abels hide"))
        self.hideLabelsButton.setShortcut(_translate("MainWindow", "L"))
        self.removeAnnotationsButton.setText(_translate("MainWindow", "(R)emove"))
        self.removeAnnotationsButton.setShortcut(_translate("MainWindow", "R"))
        self.ClearAnnotationsButton.setText(_translate("MainWindow", "(C)lear"))
        self.ClearAnnotationsButton.setShortcut(_translate("MainWindow", "C"))
        self.detectAnnotationsButton.setText(_translate("MainWindow", "(D)etect "))
        self.detectAnnotationsButton.setShortcut(_translate("MainWindow", "D"))
        self.addAnnotationsButton.setText(_translate("MainWindow", "(A)dd "))
        self.addAnnotationsButton.setShortcut(_translate("MainWindow", "A"))
        self.renameAnnotationsButton.setText(_translate("MainWindow", "Re(N)ame"))
        self.renameAnnotationsButton.setShortcut(_translate("MainWindow", "N"))
        self.hideAnnotationsButton.setText(_translate("MainWindow", "(H)ide"))
        self.hideAnnotationsButton.setShortcut(_translate("MainWindow", "H"))
        self.detFilterButton.setText(_translate("MainWindow", "Det. Filter"))
        self.annotationFilterButton.setText(_translate("MainWindow", "Adn. Filter"))
        self.yoloWorldButton.setText(_translate("MainWindow", "(W)Yolo World"))
        self.yoloWorldButton.setShortcut(_translate("MainWindow", "W"))
        self.detectorClassesLabel.setText(
            _translate("MainWindow", "Selected detector classes :")
        )
        self.button2.setText(_translate("MainWindow", "2"))
        self.button2.setShortcut(_translate("MainWindow", "2"))
        self.button5.setText(_translate("MainWindow", "5"))
        self.button5.setShortcut(_translate("MainWindow", "5"))
        self.button7.setText(_translate("MainWindow", "7"))
        self.button7.setShortcut(_translate("MainWindow", "7"))
        self.button8.setText(_translate("MainWindow", "8"))
        self.button8.setShortcut(_translate("MainWindow", "8"))
        self.button1.setText(_translate("MainWindow", "1"))
        self.button1.setShortcut(_translate("MainWindow", "1"))
        self.buttonOffset.setText(_translate("MainWindow", "`"))
        self.buttonOffset.setShortcut(_translate("MainWindow", "`"))
        self.button9.setText(_translate("MainWindow", "9"))
        self.button9.setShortcut(_translate("MainWindow", "9"))
        self.button10.setText(_translate("MainWindow", "10"))
        self.button10.setShortcut(_translate("MainWindow", "0"))
        self.button12.setText(_translate("MainWindow", "12"))
        self.button12.setShortcut(_translate("MainWindow", "="))
        self.button3.setText(_translate("MainWindow", "3"))
        self.button3.setShortcut(_translate("MainWindow", "3"))
        self.button11.setText(_translate("MainWindow", "11"))
        self.button11.setShortcut(_translate("MainWindow", "-"))
        self.button4.setText(_translate("MainWindow", "4"))
        self.button4.setShortcut(_translate("MainWindow", "4"))
        self.button6.setText(_translate("MainWindow", "6"))
        self.button6.setShortcut(_translate("MainWindow", "6"))
        self.detectorDetails.setText(_translate("MainWindow", "Detector details"))
        self.detectorConfidenceLabel.setText(_translate("MainWindow", "Confidence"))
        self.imageStrategyCombo.setItemText(
            0, _translate("MainWindow", "ImageStrategy")
        )
        self.detectorNmsLabel.setText(_translate("MainWindow", "NMS threshold"))
        self.detectorNmsCombo.setItemText(0, _translate("MainWindow", "NMS"))
        self.detectorNmsCombo.setItemText(1, _translate("MainWindow", "SoftNMS"))
        self.detectorEnabled.setText(_translate("MainWindow", "Is enabled?"))
        self.label_6.setText(_translate("MainWindow", "Detector details"))
        self.yoloWorldConfidenceLabel.setText(_translate("MainWindow", "Confidence"))
        self.label_8.setText(
            _translate(
                "MainWindow",
                "Enter class names separated by comma (ontology as text:label). Ex bus:autobus, person:osoba.",
            )
        )
        self.yoloWorldPrompt.setText(
            _translate("MainWindow", "bus:g.autobusy, person:i1.pieszy, car:c1.osobowe")
        )
        self.paintLabel.setText(_translate("MainWindow", "Painting Size"))
        self.label_3.setText(_translate("MainWindow", "Annotations filter"))
        self.label_5.setText(_translate("MainWindow", "Detections filter"))
        self.menuMenu.setTitle(_translate("MainWindow", "File"))
        self.menuPomoc.setTitle(_translate("MainWindow", "Help"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuAnnotations_type.setTitle(_translate("MainWindow", "Annotations as"))
        self.actionOtw_rz.setText(_translate("MainWindow", "Otwórz"))
        self.actionZamknij.setText(_translate("MainWindow", "Zamknij"))
        self.actionO_programie.setText(_translate("MainWindow", "O programie"))
        self.actionOtworzLokacje.setText(_translate("MainWindow", "Open directory"))
        self.actionOtworzLokacje.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionZamknijProgram.setText(_translate("MainWindow", "Exit"))
        self.actionZamknijProgram.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actionZapisz.setText(_translate("MainWindow", "Save"))
        self.actionZapisz.setShortcut(_translate("MainWindow", "Ctrl+S", "S"))
        self.actionNextLocation.setText(_translate("MainWindow", "Następna lokacja"))
        self.actionNextLocation.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionPrevLocation.setText(_translate("MainWindow", "Poprzednia lokacja"))
        self.actionPrevLocation.setShortcut(_translate("MainWindow", "Ctrl+B"))
        self.actionMountRO.setText(_translate("MainWindow", "Przemontuj lokacje"))
        self.actionNextConfiguration.setText(
            _translate("MainWindow", "Następna konfiguracja")
        )
        self.actionNextConfiguration.setShortcut(_translate("MainWindow", "Ctrl+."))
        self.actionPrevConfiguration.setText(
            _translate("MainWindow", "Poprzednia konfiguracja")
        )
        self.actionPrevConfiguration.setShortcut(_translate("MainWindow", "Ctrl+,"))
        self.actionSave_screenshoot.setText(
            _translate("MainWindow", "Save screenshoot")
        )
        self.actionSave_screenshoot.setShortcut(_translate("MainWindow", "Shift+S"))
        self.actionSave_copy.setText(_translate("MainWindow", "Save copy"))
        self.actionSave_copy.setShortcut(_translate("MainWindow", "Shift+C"))
        self.action_annotations_default.setText(_translate("MainWindow", "Default"))
        self.action_annotations_confidence_heat.setText(
            _translate("MainWindow", "Confidence Heat")
        )


from ViewerEditorImage import ViewerEditorImage
import tango_rc
